CREATE DATABASE IF NOT EXISTS SGH;
USE SGH;

CREATE TABLE IF NOT EXISTS SGH_USUARIO
(
	USR_ID INT AUTO_INCREMENT,
    USR_EMAIL VARCHAR(150) NOT NULL UNIQUE,
    USR_NOME VARCHAR(150) NOT NULL,
    USR_SENHA VARCHAR(300) NOT NULL,
    CONSTRAINT PK_USR PRIMARY KEY (USR_ID)
);

CREATE TABLE IF NOT EXISTS SGH_HORARIO_TRABALHADO
(
	HT_ID INT AUTO_INCREMENT,
    HT_USR_ID INT NOT NULL,
	HT_PJT_ID INT NOT NULL,
    HT_INICIO TIMESTAMP NOT NULL,
    HT_TERMINO TIMESTAMP NOT NULL,
    HT_FLAG_T BOOLEAN NOT NULL,
    CONSTRAINT PK_HT PRIMARY KEY (HT_ID),
    CONSTRAINT FK_USR FOREIGN KEY (HT_USR_ID) REFERENCES SGH_USUARIO (USR_ID),
    CONSTRAINT FK_PJT FOREIGN KEY (HT_PJT_ID) REFERENCES SGH_PROJETOS (PJT_ID)
);

CREATE TABLE IF NOT EXISTS SGH_PROJETO
(
	PJT_ID INT AUTO_INCREMENT,
    PJT_NOME VARCHAR(150) NOT NULL UNIQUE,
    CONSTRAINT PK_PJT PRIMARY KEY (PJT_ID)
);